# Generated by Django 5.2.11 on 2026-02-15 18:46

import api_services.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeHistory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api_services.utils.hex_uuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resume_text", models.TextField()),
                ("job_description", models.TextField()),
                ("ai_analysis", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
